Cmfour/config/routes.rb
Cmfour::Application.routes.draw do
  resources :movies

  resources :directors

end

Cmfour/app/models/director.rb
class Director < ActiveRecord::Base
  attr_accessible :dob, :name

  has_many :movies
end

Cmfour/app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :director_id, :title, :year

  belongs_to :director
end

Cmfour/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Cmfour/app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directors }
    end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @director = Director.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/new
  # GET /directors/new.json
  def new
    @director = Director.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/1/edit
  def edit
    @director = Director.find(params[:id])
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(params[:director])

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render json: @director, status: :created, location: @director }
      else
        format.html { render action: "new" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directors/1
  # PUT /directors/1.json
  def update
    @director = Director.find(params[:id])

    respond_to do |format|
      if @director.update_attributes(params[:director])
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url }
      format.json { head :no_content }
    end
  end
end

Cmfour/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

Cmfour/app/helpers/application_helper.rb
module ApplicationHelper
end

Cmfour/app/helpers/directors_helper.rb
module DirectorsHelper
end

Cmfour/app/helpers/movies_helper.rb
module MoviesHelper
end

Cmfour/app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Cmfour/app/views/directors/edit.html.erb
<h1>Editing director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

Cmfour/app/views/directors/index.html.erb
<h1>Listing directors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Dob</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @directors.each do |director| %>
  <tr>
    <td><%= director.name %></td>
    <td><%= director.dob %></td>
    <td><%= link_to 'Show', director %></td>
    <td><%= link_to 'Edit', edit_director_path(director) %></td>
    <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Director', new_director_path %>

Cmfour/app/views/directors/new.html.erb
<h1>New director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

Cmfour/app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @director.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @director.dob %>
</p>


<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>

Cmfour/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cmfour</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Cmfour/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :director_id %><br />
    <%= f.number_field :director_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Cmfour/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

Cmfour/app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Year</th>
    <th>Director</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.year %></td>
    <td><%= movie.director_id %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

Cmfour/app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

Cmfour/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Director:</b>
  <%= @movie.director_id %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>